name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: ${{ secrets.HOOK_URL }}
          webhook_secret: ${{ secrets.HOOK_KEY }}
